### ISSUE TITLE
how to deploy to android??

### ISSUE THREAD

**Issue by Alii-isk** [Nippon2019/Handwritten-Japanese-Recognition#2]
i read your article at towardsdatascience and its quiet good but you only talked about iOS deployment can u tell me how can i make it work on the android as well thank u

**Comment by Nippon2019** [comment]
Thanks for reading my article! Unfortunately, I only implemented my project for iOS, and didn’t try out android deployment (I think you will need to use android studio). But if you're working on a project, I’d be happy to help!

**Comment by Alii-isk** [comment]
> Thanks for reading my article! Unfortunately, I only implemented my project for iOS, and didn’t try out android deployment (I think you will need to use android studio). But if you're working on a project, I’d be happy to help!

Just a quick question do i have to gray scale the pained image before feeding it to the model?

**Comment by Nippon2019** [comment]
Yep, if you want the model be able to detect grayscale image then you need to convert it before training the model.
