### ISSUE TITLE
Unpack code ?

### ISSUE THREAD

**Issue by NguyenThaiHoc1** [Nippon2019/Handwritten-Japanese-Recognition#3]
Hi Author 
I confuse about unpack code "2H8sI4B4H2B30x8128s11x" where i find this code ?

Thanks you for reading
Thai Hoc

**Comment by Nippon2019** [comment]
Hi! 
Thanks for the comment. I found it on the ETL website when I worked on the project - it is just a way to extract the data of the Japanese characters.

**Comment by zalavari** [comment]
I was stunned first too, but it's pretty straightforward, if you analyze the [dataformat](http://etlcdb.db.aist.go.jp/etlcdb/etln/form_e8g.htm) and the [python struct reference](https://docs.python.org/3/library/struct.html#format-strings).

The important thing really is the `8128s` near the end, which corresponds the 8128 bytes of the actual image data, and later can be accessed with r[14].
